// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCF8Hkss4JxlKN_xgceo8WvtB2gTrNd18s',
    appId: '1:692640488115:web:5e8bedf3426ee3cbd1eec6',
    messagingSenderId: '692640488115',
    projectId: 'socialmedia-app-38914',
    authDomain: 'socialmedia-app-38914.firebaseapp.com',
    databaseURL: 'https://socialmedia-app-38914-default-rtdb.firebaseio.com',
    storageBucket: 'socialmedia-app-38914.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCS7-qJRHClDy3G9ac7yFvxPRuA28nBR1E',
    appId: '1:692640488115:android:92e5216bb5aad7ced1eec6',
    messagingSenderId: '692640488115',
    projectId: 'socialmedia-app-38914',
    databaseURL: 'https://socialmedia-app-38914-default-rtdb.firebaseio.com',
    storageBucket: 'socialmedia-app-38914.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdbXIl3YQk6v2Om1f3Qdvpt_zx9YlTUTE',
    appId: '1:692640488115:ios:4e60beb0abcee72cd1eec6',
    messagingSenderId: '692640488115',
    projectId: 'socialmedia-app-38914',
    databaseURL: 'https://socialmedia-app-38914-default-rtdb.firebaseio.com',
    storageBucket: 'socialmedia-app-38914.appspot.com',
    iosClientId: '692640488115-dinmiv0vm75b2q5a069jae64oea2ip2b.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdbXIl3YQk6v2Om1f3Qdvpt_zx9YlTUTE',
    appId: '1:692640488115:ios:13b89cb4474c6649d1eec6',
    messagingSenderId: '692640488115',
    projectId: 'socialmedia-app-38914',
    databaseURL: 'https://socialmedia-app-38914-default-rtdb.firebaseio.com',
    storageBucket: 'socialmedia-app-38914.appspot.com',
    iosClientId: '692640488115-fddl3dpq8iubm796locutqkvbh3h5n5i.apps.googleusercontent.com',
    iosBundleId: 'com.example.socialmediaApp.RunnerTests',
  );
}
